<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE aviso [
	<!ELEMENT aviso (titulo+)>
	<!ATTLIST titulo tit (#CDATA) "..." #REQUIRED>
	<!ELEMENT titulo (parrafo+,grafico*)>
	<!ELEMENT parrafo (#PCDATA)>
	<!ELEMENT grafico (#PCDATA)>
]>

<aviso>
	<titulo tit="...">
		<parrafo>...</parrafo>
		<grafico>...</grafico>
	</titulo>
	<titulo tit="...">
		<parrafo>...</parrafo>
		<grafico>...</grafico>
	</titulo>
</aviso>
