<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE aviso [
	<!ELEMENT aviso (titulo?,parrafo+,grafico*)>
	<!ELEMENT parrafo (#PCDATA)>
	<!ELEMENT grafico (#PCDATA)>
]>

<aviso>
	<parrafo>...</parrafo>
	<grafico>...</grafico>
	<parrafo>...</parrafo>
	<parrafo>...</parrafo>
	<grafico>...</grafico>
</aviso>
